// Generated by `cargo test -p analytics`. Do not edit by hand.
// Source of truth: crates/analytics/src/flags.rs

/** Every feature flag key known to the application. */
export type FlagKey =
  | "session_references_popover";

/**
 * Each flag's default, mirrored from the Rust registry.
 * The renderer reads these until the resolved registry
 * arrives, and keeps them if it never does.
 */
export const FLAG_DEFAULTS: Record<FlagKey, boolean> = {
  session_references_popover: false,
};
