[package]
name = "git"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
git2 = { version = "0.18", features = ["vendored-libgit2", "vendored-openssl"] }
log-types = { path = "../log-types" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
tempfile = "3"
