// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent profile (human or LLM agent)
 *
 * Represents an agent that can work on tasks, including both human users
 * and AI assistants.
 */
export type AgentProfile = { id: string, provider: string | null, model: string | null, type: string, capabilities: Record<string, unknown> | null, owner_user_id: string | null, created_at: string, updated_at: string, };
