// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Asset image (deduplicated by hash)
 *
 * Stores image metadata with SHA-256 hash for deduplication.
 */
export type AssetImage = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: number, hash: string, created_at: string, updated_at: string, };
