// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Draft type for task drafts
 */
export type DraftType = "initial" | "retry" | "follow_up";
