// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the forked session inherits its conversation.
 */
export type ForkMode = "native" | "digest";
