// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The point a fork branched from.
 *
 * The conversation side (`run_id`, and the executor's message id when it has
 * one) always exists. The git side does not: General chats and non-git
 * projects have no commit to anchor to, so `commit` is None there.
 */
export type ForkAnchor = { run_id: string, message_uuid: string | null, commit: string | null, };
