// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a completed delegated run handed back.
 *
 * The conversation side (`run_id`) always exists. The git side does not:
 * General chats and non-git projects produce no commit, so `commit` and
 * `branch` are None there.
 */
export type HandoffInfo = { run_id: string, commit: string | null, branch: string | null, 
/**
 * True once this handoff has been pushed into the delegating session (the
 * barrier wake). Undelivered handoffs accumulate until every delegated
 * sibling is terminal, then ship together in one wake.
 */
delivered: boolean, };
