// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Merge record type (direct merge commit or pull request tracking)
 */
export type MergeType = "direct" | "pr";
