// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task run status
 */
export type RunStatus = "pending" | "running" | "completed" | "failed" | "cancelled";
