// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task run logs (local execution only, chunked storage)
 *
 * Stores logs in NDJSON format, split into chunks to avoid hitting
 * database size limits. Each chunk is max 10MB.
 */
export type TaskRunLog = { task_run_id: string, sequence_number: number, logs_jsonl: string, byte_size: number, inserted_at: string, };
