// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./task-status";

/**
 * Task record (core entity)
 *
 * Represents a task with its current state, references, and metadata.
 * This is the central entity in the Task-centric design.
 */
export type TaskRecord = { id: string, slug: string | null, project_id: string, parent_task_id: string | null, title: string, description: string | null, status: TaskStatus, due_at: string | null, branch: string | null, 
/**
 * Local execution only: worktree path for isolation
 */
worktree_path: string | null, worktree_deleted: boolean, 
/**
 * FK to current active session
 */
active_session_id: string | null, 
/**
 * Runtime flag: the agent is blocked on an AskUserQuestion approval and is
 * waiting for the user to answer. Cleared when the question resolves or the
 * active session ends. Denormalized runtime state mirroring
 * `active_session_id`; never true while there is no active session.
 */
awaiting_input: boolean, created_at: string, updated_at: string, 
/**
 * Position within a kanban column (lower = higher). 0 means unordered.
 */
sort_order: number, 
/**
 * Bare agent kind the task last ran with (e.g. "CLAUDE_CODE", "CODEX").
 * Denormalized from the latest run's executor so UIs can show the agent
 * logo without a per-task run lookup. `None` until the first run.
 */
last_executor: string | null, 
/**
 * One-line outcome of the latest completed run, derived from the final
 * assistant message at run-completion time. Denormalized like
 * `last_executor` so list surfaces can show "what this session did"
 * without a transcript lookup. `None` until a run completes.
 */
last_summary: string | null, 
/**
 * Title of the session this one was forked from, snapshotted at fork time.
 *
 * Read from the fork edge rather than stored on the row, but carried here
 * so the session list can render provenance without a per-task lookup. A
 * snapshot, not a live join to the source's current title: the source can
 * be renamed or deleted without breaking this label.
 */
forked_from_title: string | null, 
/**
 * Title of the task that delegated this one, snapshotted at delegation
 * time. Same denormalization contract as `forked_from_title`, read from
 * the delegate edge.
 */
delegated_from_title: string | null, };
