// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task image link (many-to-many relationship)
 *
 * Links tasks to images, preventing duplicate attachments via UNIQUE constraint.
 */
export type TaskImageLink = { id: string, task_id: string, image_id: string, created_at: string, };
