// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftType } from "./draft-type";

/**
 * Task draft (prompt drafts, retries, follow-ups)
 *
 * Represents a draft prompt or retry attempt for a task.
 */
export type TaskDraft = { id: string, task_id: string, retry_task_run_id: string | null, draft_type: DraftType, prompt: string | null, image_ids: string | null, queued: boolean, sending: boolean, version: number, variant: string | null, created_at: string, updated_at: string, };
