// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task template (reusable task definitions)
 *
 * Templates can be global (project_id = NULL) or project-specific.
 */
export type TaskTemplate = { id: string, project_id: string | null, template_name: string, title: string, description: string | null, created_at: string, updated_at: string, };
