// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeStatus } from "./merge-status";
import type { MergeType } from "./merge-type";

/**
 * Task merge (PR/merge tracking)
 *
 * Tracks pull requests and merge operations for a task.
 */
export type TaskMerge = { id: string, task_id: string, merge_type: MergeType, target_branch_name: string | null, merge_commit: string | null, pr_number: bigint | null, pr_url: string | null, pr_status: MergeStatus | null, pr_merged_at: string | null, pr_merge_commit_sha: string | null, created_at: string, reverted_at: string | null, };
