// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecurrenceStatus } from "./recurrence-status";

/**
 * Task recurrence (scheduled recurring tasks)
 *
 * Manages recurring task schedules and tracks the last generated task.
 */
export type TaskRecurrence = { id: string, project_id: string, parent_task_id: string | null, last_task_id: string | null, title: string, description: string | null, image_ids: string | null, starts_at: string | null, frequency: string | null, interval: number | null, timezone: string | null, status: RecurrenceStatus, next_run_at: string | null, last_run_at: string | null, created_at: string, updated_at: string, };
