// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionMode } from "./execution-mode";
import type { RunStatus } from "./run-status";

/**
 * Task run (execution history)
 *
 * Represents a single execution of a task. Multiple runs can exist per task.
 * Supports both local (worktree) and remote (Northflank Job) execution modes.
 */
export type TaskRun = { id: string, task_id: string, execution_mode: ExecutionMode, status: RunStatus, run_reason: string | null, executor_action: string | null, executor_action_type: string | null, exit_code: number | null, dropped: boolean, before_head_commit: string | null, after_head_commit: string | null, branch_name: string | null, target_branch: string | null, container_ref: string | null, workspace_path: string | null, executor_label: string | null, resume_session_id: string | null, worktree_deleted: boolean, executor_job_id: string | null, s3_prefix: string | null, logs_uri: string | null, summary_uri: string | null, diffs_prefix: string | null, logs_retrieval_failed: boolean, started_at: string | null, completed_at: string | null, created_at: string, updated_at: string, };
