// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task session (agent interaction session)
 *
 * Represents a session where an agent (human or LLM) works on a task.
 * Sessions can be handed off between agents.
 */
export type TaskSession = { id: string, task_id: string, task_run_id: string | null, agent_profile_id: string, external_session_id: string | null, prompt: string | null, summary: string | null, handoff_from_session_id: string | null, worktree_commit: string | null, state_snapshot: Record<string, unknown> | null, created_at: string, updated_at: string, };
