// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task record status
 */
export type TaskStatus = "pending" | "in_progress" | "completed" | "failed" | "cancelled";
