// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskContextRef = { id: string, task_id: string, task_session_id: string | null, task_run_id: string | null, kind: string, target_task_id: string | null, target_session_id: string | null, path: string | null, branch: string | null, mode: string, label: string | null, metadata_json: string | null, sort_order: number, created_at: string, updated_at: string, };
