// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskContextRefInput = { kind: string, target_task_id: string | null, target_session_id: string | null, path: string | null, branch: string | null, mode: string | null, label: string | null, metadata_json: string | null, };
