// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a single agent CLI: where it resolved and what version it reports.
 */
export type CliStatus = { 
/**
 * Manifest name, e.g. `"claude"`, `"codex"`, `"pi"`.
 */
name: string, 
/**
 * Whether a binary was resolved at all.
 */
found: boolean, 
/**
 * Absolute resolved path, when found.
 */
path: string | null, 
/**
 * Human-readable locator for how it resolved.
 */
source: string | null, 
/**
 * Raw first line of `<cli> --version`, when the probe succeeded.
 */
version: string | null, 
/**
 * Install hint from the manifest, shown when the CLI is missing.
 */
install_hint: string, };
