// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured pi credential, without its secret.
 */
export type PiCredentialInfo = { provider: string, 
/**
 * Credential kind reported by pi: `api_key`, `oauth`, or `unknown`.
 */
kind: string, };
