// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable pi model. `value` is pi's `provider/id` form (accepted
 * verbatim by `pi --model`); `label` is the human-facing name.
 */
export type PiModelOption = { value: string, label: string, provider: string, };
